### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
What does it do?

**Comment by UnixJunkie** [comment]
Is this continuous integration related?
How can I test that it is working?

**Comment by liyishuai** [comment]
Yes, here's the triggered CI: https://github.com/liyishuai/ocamlscript/actions/runs/1379335056

**Comment by UnixJunkie** [comment]
The seven warnings are fine?

**Comment by liyishuai** [comment]
The warning says the executable `ocamlscript` was not found in the Windows build. Does Windows have the Makefile variable `EXE` set to, say, `.exe`?

---
Update: Indeed, https://github.com/ocaml-community/ocamlscript/blob/89546932729b99a6b683db13b74aac1b97b467d8/OCamlMakefile#L127-L130

New run: https://github.com/liyishuai/ocamlscript/actions/runs/1379644564
Ready to merge if artifact warnings are cleared. Ignore `macOS-latest workflows will use macOS-11 soon.`

**Comment by liyishuai** [comment]
Ready.

**Comment by UnixJunkie** [comment]
Ok, thanks for the details and for your contribution.
Sorry, for the maybe dumb questions: I don't know nor use github actions.

**Pull request merged**
